[build]
  command = "npm run build"
  publish = "../frontend-origination-dist"

[[redirects]]
  from = "/api/*"
  to = "https://bondly.co.za/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
